sharemindteam/sharemind-client

- src/Router.tsx
- src/components/Common/Header.tsx
- src/components/Common/TabA1.tsx
- src/pages/Buyer/BuyerConsult.tsx
<br>
<br>
<br>
TabA1에 navigate 살짝 수정
<br>
> [Feature] TabA1 navigate 수정

- package-lock.json
- package.json
- src/components/Buyer/CartegorySearch.tsx
- src/components/Common/AppContainer.tsx
- src/components/Common/Header.tsx
- src/components/Common/TabA1.tsx
- src/pages/Buyer/BuyerHome.tsx
- src/styles/GlobalStyle.ts
- src/styles/font.tsx
- src/utils/constant.ts
<br>
<br>
<br>
Header와 TabA1 position sticky로 바꿈
<br>
> [Feature] 공통컴포넌트 수정

- src/components/Common/AppContainer.tsx
- src/styles/GlobalStyle.ts
<br>
<br>
<br>
height로 인한 문제 scroll 로 해결
<br>
> fix: height scroll 문제 fix (#5)

- src/styles/font.tsx
<br>
<br>
<br>
font family 추가 안했었다...
<br>
> [fix] font family 추가 안했었음(#2)

- src/styles/font.tsx
<br>
<br>
<br>
font.tsx padding margin props 추가
<br>
> [Feature] font.tsx padding margin props 추가

- src/Router.tsx
- src/components/Buyer/BuyerHome/ConsultInReady.tsx
- src/components/Buyer/BuyerLetter/LetterTags.tsx
- src/components/Buyer/BuyerPayment/PaymentCard.tsx
- src/components/Buyer/BuyerPayment/PaymentModal.tsx
- src/components/Buyer/BuyerReviewManage/ReviewManageCard.tsx
- src/components/Buyer/Common/SearchResults.tsx
- src/pages/Buyer/BuyerConsult.tsx
- src/pages/Buyer/BuyerCounselorProfile.tsx
- src/pages/Buyer/BuyerLetter.tsx
- src/pages/Buyer/BuyerMypage.tsx
- src/pages/Buyer/BuyerPayment.tsx
- src/pages/Buyer/BuyerReviewManage.tsx
- src/pages/Buyer/BuyerWriteReview.tsx
- src/utils/atom.ts
- src/utils/buyerDummy.ts
- src/utils/counselorDummy.ts
<br>
<br>
<br>
결제 내역 페이지 구현 완료
<br>
<br>
편지 페이지 살짝 들어가버렸는데 아직 미구현 입니당
<br>
> [Feature]결제 내역 페이지 구현 완료

- src/api/get.ts
- src/components/Seller/SellerLetter/LetterBonusQuestionStep.tsx
- src/components/Seller/SellerLetter/LetterTagListSection.tsx
- src/pages/Seller/SellerLetter.tsx
- src/utils/type.ts
<br>
<br>
UI 구현보다 5000배 재밌네
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>
> [Feature] 판매자 편지 GET METHOD 모두 연결하여 상태 반영

- .gitignore
- src/Router.tsx
- src/api/axios.ts
- src/api/get.ts
- src/api/patch.ts
- src/api/post.ts
- src/components/Buyer/BuyerConsult/ConsultModal.tsx
- src/components/Buyer/BuyerHome/ConsultInProgress.tsx
- src/components/Buyer/BuyerLetter/LetterMainSection.tsx
- src/components/Buyer/BuyerLetterWrite/LetterLoadModal.tsx
- src/components/Buyer/BuyerLetterWrite/LetterSaveModal.tsx
- src/components/Buyer/BuyerLetterWrite/LetterWriteModal.tsx
- src/components/Buyer/Common/ConsultCard.tsx
- src/pages/Buyer/BuyerConsult.tsx
- src/pages/Buyer/BuyerLetter.tsx
- src/pages/Buyer/BuyerLetterWrite.tsx
- src/pages/Common/Admin.tsx
- src/utils/convertCategoryEnum.tsx
> [Feature] 편지 구현 중간 pr

- src/api/patch.ts
- src/components/Buyer/BuyerLetterWrite/LetterSaveModal.tsx
- src/components/Buyer/BuyerLetterWrite/LetterWriteModal.tsx
- src/pages/Buyer/BuyerLetter.tsx
- src/pages/Buyer/BuyerLetterWrite.tsx
<br>
<br>
<br>
임시저장 로직까지 완성하고 제출하고 제출 결과만 띄워주면 끝
<br>
> [Feature] 편지 페이지 임시저장까지 완료

- src/api/get.ts
- src/api/patch.ts
- src/api/post.ts
- src/components/Seller/Common/OngoingCounsultBox.tsx
- src/components/Seller/SellerLetter/LetterBonusQuestionStep.tsx
- src/components/Seller/SellerLetter/LetterBonusReplyStep.tsx
- src/components/Seller/SellerLetter/LetterQuestionStep.tsx
- src/components/Seller/SellerLetter/LetterReplyStep.tsx
- src/components/Seller/SellerLetterWrite/LetterIsSaveModal.tsx
- src/components/Seller/SellerLetterWrite/LetterPostModal.tsx
- src/components/Seller/SellerLetterWrite/LetterSavePostModal.tsx
- src/components/Seller/SellerLetterWrite/LetterWriteHeader.tsx
- src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
- src/components/Seller/SellerVerifyQuiz/IsSubmitQuizModal.tsx
- src/pages/Seller/SellerLetter.tsx
- src/pages/Seller/SellerLetterWrite.tsx
<br>
<br>
<br>
하~~ 
<br>
<br>
<br>
> 상담사 편지 API 연동, 퀴즈 API 연동 (POST)

- src/api/axios.ts
- src/components/Buyer/BuyerLetter/LetterMainSection.tsx
- src/components/Buyer/BuyerLetterWrite/LetterLoadModal.tsx
- src/components/Buyer/BuyerLetterWrite/LetterPostModal.tsx
- src/components/Buyer/BuyerSignup/SignupInfo.tsx
- src/components/Buyer/BuyerSignup/SignupModal.tsx
- src/components/Buyer/BuyerSignup/SignupPw.tsx
- src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
- src/components/Buyer/Common/ConsultCard.tsx
- src/pages/Buyer/BuyerConsult.tsx
- src/pages/Buyer/BuyerLetter.tsx
- src/pages/Buyer/BuyerLetterWrite.tsx
- src/styles/font.tsx
- src/utils/LoadingSpinner.tsx
- src/utils/atom.ts
- src/utils/type.ts
> [Feature] 구매자 편지 완료

- src/api/get.ts
- src/api/patch.ts
- src/components/Common/Profile.tsx
- src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/UpdatePopup.tsx
- src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
- src/components/Seller/SellerVerifyQuiz/IsSubmitQuizModal.tsx
- src/hooks/useCustomSelect.ts
- src/pages/Seller/SellerMyPageModifyProfile.tsx
- src/pages/Seller/SellerMyPageViewProfile.tsx
- src/pages/Seller/SellerMypage.tsx
- src/pages/Seller/SellerVerifyQuiz.tsx
- src/utils/categoryInputmaker.ts
- src/utils/convertStringToCharNum.ts
<br>
<br>
<br>
남은 판매자 쪽 API 연동하려면 어드민에서 프로필 심사 승인해줘야할듯
<br>
<br>
<br>
> [Feature] 판매자 프로필 보기, 편집 API 연동

- package-lock.json
- package.json
- src/Router.tsx
- src/api/get.ts
- src/api/patch.ts
- src/components/Buyer/BuyerLogin/LoginModal.tsx
- src/components/Buyer/BuyerSearch/SearchRecent.tsx
- src/pages/Buyer/BuyerLogin.tsx
- src/pages/Buyer/BuyerLogout.tsx
- src/pages/Common/Admin.tsx
- src/utils/atom.ts
<br>
<br>
<br>
로그인, 회원가입, 로그아웃, 어드민 페이지 최종완료
<br>
> [Feature]  로그인, 회원가입, 로그아웃, 어드민 페이지 최종완료

- src/api/get.ts
- src/components/Seller/Common/OngoingCounsultBox.tsx
- src/components/Seller/SellerHome/ConsultReviewsSection.tsx
- src/components/Seller/SellerMyPageReview/SellerReviewMainSection.tsx
<br>
<br>
<br>
가보자
<br>
<br>
<br>
> [Feature] 마인더 리뷰 컨트롤러 연동 

- src/components/Common/Input.tsx
- src/components/Common/Profile.tsx
- src/components/Seller/Common/BottomButton.tsx
- src/components/Seller/SellerMyPageModifyProfile/ModifyProfileHeader.tsx
- src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/StyleModal.tsx
- src/components/Seller/SellerMyPageViewProfile/NoProfileSection.tsx
- src/components/Seller/SellerMyPageViewProfile/ViewProfileHeader.tsx
- src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
- src/hooks/useCustomSelect.ts
- src/hooks/useInput.ts
- src/pages/Seller/SellerMyPageModifyProfile.tsx
- src/pages/Seller/SellerMyPageViewProfile.tsx
- src/pages/Seller/SellerVerifyQuiz.tsx
<br>
<br>
<br>
무한도전보면서 하느라 코딩효율 개떨어짐
<br>
<br>
<br>
> 마인더 판매정보 섹션 API 예외처리 및 자잘한 디자인 반영

- src/api/get.ts
- src/components/Seller/SellerConsult/SellerConsultSection.tsx
- src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/IsOutPopup.tsx
- src/components/Seller/SellerMyPageModifyProfile/ModifyProfileHeader.tsx
- src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
- src/components/Seller/SellerMyPageModifyProfile/UpdatePopup.tsx
- src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
- src/pages/Seller/SellerMyPageModifyProfile.tsx
- src/pages/Seller/SellerMyPageViewProfile.tsx
- src/utils/atom.ts
- src/utils/convertTimeToString.ts
- src/utils/formatTimeRange.ts
<br>
<br>
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>
> [Feature] 상담 시간 선택 완전히 구현, 편지 보충, API 주소 바뀐 것 반영

- src/components/Buyer/BuyerAvailCounselor/AvailCounselorSearchResult.tsx
- src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
- src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
- src/components/Buyer/BuyerSearchResult/SearchResults.tsx
- src/components/Buyer/Common/ReadyConsultCard.tsx
- src/pages/Buyer/BuyerCounselorProfile.tsx
- src/pages/Buyer/BuyerHome.tsx
- src/utils/atom.ts
- src/utils/type.ts
> feat: 요일 불필요하게 뜨는 문제 해결 (#46)

- src/Router.tsx
- src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
- src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
- src/pages/Buyer/BuyerConsultRequest.tsx
- src/pages/Buyer/BuyerCounselorProfile.tsx
- src/pages/Buyer/BuyerPaymentDetail.tsx
- src/pages/Seller/SellerPwChange.tsx
<br>
<br>
상담 결제하기 연동 및 회원가입 이메일 maxlength 수정 
<br>
> [fix] 상담 결제하기 연동 및 회원가입 이메일 maxlength 수정 

- src/components/Common/Profile.tsx
- src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
- src/components/Seller/SellerVerifyMaterial/VerifyMaterialButton.tsx
- src/pages/Seller/SellerMyPageModifyProfile.tsx
- src/pages/Seller/SellerMypage.tsx
- src/pages/Seller/SellerVerifyQuiz.tsx
<br>
<br>
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>
> 마인더 프로필 인증 실패 시 버튼 비활성화 및 프로필 예외처리

- src/api/get.ts
- src/api/patch.ts
- src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
- src/components/Buyer/BuyerCounselorProfile/CounselorProfileCard.tsx
- src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
- src/components/Buyer/Common/ReadyConsultCard.tsx
- src/components/Buyer/Common/SearchResults.tsx
- src/pages/Buyer/BuyerCounselorProfile.tsx
- src/pages/Buyer/BuyerSearchResult.tsx
- src/utils/type.ts
<br>
<br>
<br>
마인더 프로필 페이지 구현 및 상담사 카드 오류 수정
<br>
> [Feature] 마인더 프로필 페이지 구현 및 상담사 카드 오류 수정

- package-lock.json
- package.json
- src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
- src/pages/Buyer/BuyerChat.tsx
- src/pages/Buyer/BuyerReviewManage.tsx
- src/pages/Buyer/BuyerSavedCounselor.tsx
- src/socket.d.ts
<br>
<br>
<br>
채팅 라이브러리 import 성공
<br>
> [Feature] 채팅 라이브러리 import 성공 

- src/api/patch.ts
- src/api/post.ts
- src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/pages/Buyer/BuyerLogin.tsx
- src/pages/Buyer/BuyerPwChange.tsx
- src/pages/Buyer/BuyerReviewManage.tsx
<br>
<br>
<br>
비밀번호 변경 api 연동 완료 및 리뷰관리 페이지 무한스크롤 구현
<br>
> [Feature] 비밀번호 변경 api 연동 완료 및 리뷰관리 페이지 무한스크롤 구현

- src/components/Seller/SellerConsult/SellerConsultSection.tsx
- src/components/Seller/SellerLetter/LetterHeader.tsx
- src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
- src/components/Seller/SellerMyPageReview/SellerReviewMainSection.tsx
- src/components/Seller/SellerMyPageViewProfile/NoProfileSection.tsx
- src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
- src/pages/Seller/SellerLetter.tsx
- src/pages/Seller/SellerMyPageModifyProfile.tsx
<br>
<br>
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>
> [Feature] 판매자 profile_Status 에 따른 페이지 접근 권한 부여 및 편지 추가된 API 연동

- src/components/Common/AppContainer.tsx
- src/pages/Buyer/BuyerMypage.tsx
- src/pages/Buyer/BuyerSearchResult.tsx
> [Feature] chore 서비스 소개 navigate 추가

- src/Router.tsx
- src/api/get.ts
- src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
- src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/components/Buyer/BuyerSearch/SearchHeader.tsx
- src/components/Buyer/BuyerSearchResult/SearchResults.tsx
- src/components/Buyer/Common/ReadyConsultCard.tsx
- src/components/Common/AppContainer.tsx
- src/components/Common/TabA1.tsx
- src/pages/Buyer/BuyerAvailCounselor.tsx
- src/pages/Buyer/BuyerCategoryResult.tsx
- src/pages/Buyer/BuyerConsult.tsx
- src/pages/Buyer/BuyerCounselorProfile.tsx
- src/pages/Buyer/BuyerHome.tsx
- src/pages/Buyer/BuyerLogin.tsx
- src/pages/Buyer/BuyerMypage.tsx
- src/pages/Buyer/BuyerPaymentComplete.tsx
- src/pages/Buyer/BuyerReviewManage.tsx
- src/pages/Buyer/BuyerSavedCounselor.tsx
- src/pages/Buyer/BuyerSearchResult.tsx
- src/pages/Buyer/BuyerSignupComplete.tsx
- src/pages/Common/Service.tsx
<br>
<br>
<br>
검색 관련 무한 스크롤 구현 및 홈 url /share로 이동
<br>
> [Feature] 검색 관련 무한 스크롤 구현 및 홈 url /share로 이동

- src/Router.tsx
- src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/components/Buyer/BuyerPayment/PaymentCard.tsx
- src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorResults.tsx
- src/components/Buyer/Common/SortModal.tsx
- src/pages/Buyer/BuyerCategoryResult.tsx
- src/pages/Buyer/BuyerConsult.tsx
- src/pages/Buyer/BuyerPayment.tsx
- src/pages/Buyer/BuyerPaymentDetail.tsx
- src/pages/Buyer/BuyerReviewManage.tsx
- src/pages/Buyer/BuyerSavedCounselor.tsx
- src/pages/Buyer/BuyerSearchResult.tsx
- src/utils/pending.ts
- src/utils/type.ts
<br>
<br>
<br>
무한스크롤 구현완료 외 자잘
<br>
> [Feature] 무한스크롤 구현완료 외 자잘

- src/App.tsx
- src/api/get.ts
- src/api/patch.ts
- src/components/Seller/Common/OngoingCounsultBox.tsx
- src/components/Seller/SellerConsult/SellerConsultSection.tsx
- src/components/Seller/SellerHome/IncomeManagementSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
- src/components/Seller/SellerMyPageReview/SellerReviewMainSection.tsx
- src/components/Seller/SellerVerifyQuiz/VerifySuccess.tsx
- src/pages/Seller/SellerCalculateManagement.tsx
- src/pages/Seller/SellerMypage.tsx
<br>
<br>
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>
> [Feature] 수익 관리 api 연결, 그 외 자잘한 반영사항들

- src/pages/Buyer/BuyerAvailCounselor.tsx
- src/pages/Buyer/BuyerConsult.tsx
<br>
<br>
<br>
들준마페이지 props 오류 해결
<br>
> [Fix] 들준마페이지 props 오류 해결

- src/components/Buyer/BuyerCounselorProfile/CounselorExp.tsx
<br>
<br>
<br>
chore: 마인더 프로필 줄바꿈 추가 (#46)
<br>
> [Fix] 마인더 프로필 줄바꿈 추가 (#46)

- src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
- src/components/Buyer/Common/SortModal.tsx
- src/hooks/useDebounce.ts
- src/hooks/useIntersectionObserver.ts
- src/pages/Buyer/BuyerAvailCounselor.tsx
- src/pages/Buyer/BuyerCategoryResult.tsx
- src/pages/Buyer/BuyerPayment.tsx
- src/pages/Buyer/BuyerReviewManage.tsx
- src/pages/Buyer/BuyerSavedCounselor.tsx
- src/pages/Buyer/BuyerSearchResult.tsx
<br>
<br>
<br>
무한 스크롤 중복 api 호출 문제 fix 및 무한 스크롤 최종완료
<br>
> [Feature] 무한 스크롤 중복 api 호출 문제 fix 및 무한 스크롤 최종완료

- src/components/Common/AppContainer.tsx
- src/context/StompContent.tsx
- src/index.tsx
- src/pages/Common/Service.tsx
- src/pages/Seller/SellerCalculateManagement.tsx
- src/pages/Seller/SellerChatTemp.tsx
- src/styles/GlobalStyle.ts
- src/utils/atom.ts
- src/utils/type.ts
<br>
<br>
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>
> StompClient 전역으로 설정 중간 PR

- src/components/Seller/Common/OngoingCounsultBox.tsx
- src/components/Seller/SellerHome/OnGoingConsultSection.tsx
<br>
<br>
<br>
진중상 채팅 목록까지 고려하여 코드 수정
<br>
<br>
<br>
> [Feature] 마인더 진행중인 상담 api 연동 오류 해결 

- src/components/Seller/SellerMyPageReview/ReviewCard.tsx
- src/components/Seller/SellerMyPageReview/ReviewComplaintMenu.tsx
- src/components/Seller/SellerMyPageReview/SellerReviewMainSection.tsx
<br>
<br>
<br>
- 마인더 리뷰 페이지 무한 스크롤 구현
<br>
<br>
<br>
> [Feature] 마인더 리뷰 무한 스크롤 구현

- src/pages/Buyer/BuyerChat.tsx
- src/pages/Seller/SellerChatTemp.tsx
<br>
<br>
<br>
모바일에서 전송 시 키보드가 내려가지 않도록 수정하였습니다.
<br>
<br>
#169
<br>
> feat: maintain focus when submit

- src/pages/Common/Service.tsx
<br>
<br>
<br>
소개 페이지의 연애 카테고리 + 강아지 캐릭터 무한 스크롤을 구현
<br>
<br>
<br>
> [Feature] 소개 페이지 무한 가로 스크롤 구현

- src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
- src/pages/Buyer/BuyerFindInfo.tsx
- src/pages/Buyer/BuyerPwChange.tsx
<br>
<br>
<br>
* 비밀번호 찾기 이메일 전송 완료 시 복구 이메일로 전송완료 되었습니다 => 이메일로 ~~~ 로 수정
* 추가적으로 회원가입 시 이메일 인증번호 에러코드 409로 백엔드에서 수정되어서 반영
<br>
<br>
#168
<br>
<br>
이메일 인증번호 부분 로직만 간단하게 확인해주세용~
<br>
> chore: find pw modal text

- src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
- src/components/Seller/SellerConsult/SellerChatList.tsx
<br>
<br>
<br>
기존의 상담은 생성 시 consult tab에서 하단에 생성되었는데, 상단에 생성되도록 수정하고 WS도 처리하였습니다.
<br>
<br>
#178
<br>
> feat: insert new chat at top on consult tab (#178)

- .github/pull_request_Template.md
<br>
<br>
<br>
pr template 수정입니당
<br>
> docs: edit pr template

- src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
- src/components/Buyer/BuyerPayment/PaymentModal.tsx
- src/components/Buyer/Common/ConsultCard.tsx
- src/components/Seller/SellerConsult/SellerLetterList.tsx
- src/pages/Buyer/BuyerChat.tsx
- src/pages/Common/Admin.tsx
- src/pages/Seller/SellerChatTemp.tsx
- src/pages/Seller/SellerMyPageModifyProfile.tsx
- src/pages/Seller/SellerVerifyQuiz.tsx
<br>
<br>
<br>
셰어쪽 상담 탭 상담 완료되거나 상담 취소된 상담 블러 처리했습니다!
<br>
> feat: end consult blur

- src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
- src/components/Seller/SellerConsult/SellerChatList.tsx
<br>
<br>
<br>
기존의 상담탭 url unsubscribe url 오류 간단하게 수정했습니다.
<br>
> hotfix: ws unsubscribe url

- src/Router.tsx
- src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/components/Common/Profile.tsx
- src/components/Seller/Common/OngoingCounsultBox.tsx
- src/components/Seller/SellerConsult/SellerConsultSection.tsx
- src/components/Seller/SellerHome/ConsultReviewsSection.tsx
- src/components/Seller/SellerHome/IncomeManagementSection.tsx
- src/components/Seller/SellerHome/OnGoingConsultSection.tsx
- src/pages/Buyer/BuyerConsult.tsx
- src/pages/Buyer/BuyerOpenConsultDetail.tsx
- src/pages/Seller/SellerHome.tsx
<br>
<br>
<br>
눈에 띄는 스타일 오류들을 우선적으로 해결해봤습니다, 홈/상담/공개상담/내 정보 스타일을 통일했어용
<br>
<br>
일대다상담과 관련된 추가 마크업 작업은 한 페이지 남긴했는데 일단 중지했습니당 
<br>
> [Style] 셰어와 마인더 스타일 통일

- src/pages/Buyer/BuyerPaymentDetail.tsx
<br>
<br>
<br>
자기 자신 신청 포함 alert error message 로직 수정했습니다!
<br>
<br>
#196
<br>
<br>
error message 뒤에 value 값이 같이 들어와서 . 기준으로 끊어서 보여주게 구현했는데 한번 확인 부탁드립니다!
<br>
> feat: fix error alert

- src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
- src/components/Seller/SellerConsult/SellerChatList.tsx
- src/utils/atom.ts
<br>
<br>
<br>
* isConnected check를 통해 상담탭 채팅에서 리렌더 시 불필요한 subscribe / unsubscribe 예외처리를 하였습니다.
* 추가적으로 리렌더 시에 unsubscribe를 못하는 문제를 해결하고자 이슈를 등록하였는데, 해당 이슈가 해결된 관계로 간단한 예외처리와 함께 Pr 날립니다.
<br>
<br>
#185
<br>
<br>
간단하게 확인 부탁드립니다!
<br>
> [Feature] 불필요한 subscribe 예외처리

- src/api/axios.ts
- src/components/Buyer/BuyerQuit/QuitFooter.tsx
- src/contexts/StompContext.tsx
- src/pages/Buyer/BuyerLogin.tsx
- src/pages/Buyer/BuyerLogout.tsx
- src/pages/Buyer/BuyerPwChange.tsx
- src/pages/Seller/SellerLogout.tsx
<br>
<br>
<br>
localStorage => cookie로 jwt refactor
<br>
<br>
#176
<br>
<br>
간단하게 localStorage에서 cookie로 바꿨습니다. 확인 한번 부탁드립니다!
<br>
> refactor: change to cookie

- package-lock.json
- package.json
- src/components/Buyer/BuyerPwChange/usePwChangeInput.ts
- src/pages/Buyer/BuyerPayment.tsx
- src/pages/Buyer/BuyerPwChange.tsx
- src/utils/signupValidCheck.ts
<br>
<br>
<br>
비밀번호 일치 여부를 작성할 때, 과도한 api 호출을 방지하기 위해 `useDebounce` 커스텀 훅을 사용하여, 300ms에 한번씩 
비밀번호 일치 여부 확인 요청을 하도록 수정하였습니다.
아래 두가지 이슈까지 해결하였습니다.
* 기존에 페이지에 들어가자마자 오류 메세지가 뜨는 이슈
* 하나의 input을 작성하면 나머지 두 개의 input의 오류메세지도 뜨는 이슈
<br>
<br>
#201 
<br>
<br>
`useDebounce` 사용 로직 확인하고 나중에 비슷한 기능 구현할 때 적용시키면 좋을 것 같습니다~!
그리고 이슈 처리 과정에서 `react-use` 라이브러리 install 했는데 유용한 훅들이 많으니 한번 문서 읽어보셔도 좋을거 같습니다!
https://github.com/streamich/react-use
<br>
> [Feature] 비밀번호 변경 useDebounce 적용 및 버그 개선

- src/components/Buyer/Common/ConsultCard.tsx
- src/components/Seller/Common/OngoingCounsultBox.tsx
<br>
<br>
<br>
모바일에서 텍스트 짤림 이슈 해결
<br>
<br>
#206 
<br>
<br>
추후에 상담카드 컴포넌트도 따로 common component로 빼서 통일시키는게 좋을거 같네용 ㅎㅎ 이슈 남겨놓겠습니다!
<br>
> [Hotfix] 모바일 상담 탭 카드 텍스트 짤림 이슈 해결

- src/App.tsx
- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/contexts/StompContext.tsx
- src/pages/Buyer/BuyerMypage.tsx
<br>
<br>
<br>
홈화면에서 진행 중인 상담이 채팅일 시에 실시간으로 메세지가 오도록 구현하였습니다.
<br>
<br>
#205 
<br>
<br>
확인 부탁드립니다~
<br>
> [Feature] 홈화면에서도 채팅이 업데이트되도록 구현

- src/components/Buyer/BuyerWriteOpenConsult/FianlWritePopup.tsx
- src/components/Common/Header.tsx
- src/components/Common/TabA1.tsx
- src/components/Seller/SellerMyPageReview/SellerReviewHeader.tsx
- src/components/Seller/SellerMyPageViewProfile/NoProfileSection.tsx
- src/components/Seller/SellerMyPageViewProfile/ViewProfileHeader.tsx
- src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
- src/pages/Buyer/BuyerSavedCounselor.tsx
- src/pages/Buyer/BuyerWriteOpenConsult.tsx
- src/pages/Seller/SellerConsult.tsx
- src/pages/Seller/SellerHome.tsx
- src/pages/Seller/SellerMyPageReview.tsx
- src/pages/Seller/SellerMyPageViewProfile.tsx
- src/utils/convertStringToCharNum.ts
<br>
<br>
<br>
- 공개상담 제목, 본문 최대 입력 글자 수 각각 50글자, 1000글자 maxLength로 제한하였습니다.
- 스크롤 형태의 페이지에서 헤더가 내려가는 경우들이 있어 각 페이지마다 고정되어야 할 요소들 아래에 스크롤 컨테이너를 만들어 해결하였습니다
<br>
<br>
#210 , #224, #223
<br>
<br>
<br>
> [Fix] 공개상담 제목, 본문 최대 입력 글자 수 제한, 헤더 고정

- src/pages/Common/Service.tsx
<br>
<br>
<br>
서비스 페이지 뒤로가기 `-1` 로 수정했습니다!
<br>
> [Hotfix] 서비스 소개 페이지 navigate 처리

- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/components/Buyer/BuyerOpenConsult/HotOpenConsultList.tsx
- src/components/Buyer/BuyerOpenConsultDetail/CommentCard.tsx
- src/components/Common/TabB2.tsx
- src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
- src/components/Seller/SellerOpenConsult/CommentListSection.tsx
- src/pages/Seller/SellerOpenConsult.tsx
<br>
<br>
<br>
- 공개상담 댓글 목록 줄바꿈 반영 
- 공개상담 페이지 헤더 고정
- 눈에 보이는 쓸데없는 import 삭제 
<br>
<br>
<br>
<br>
<br>
> [Hotfix] 공개상담 댓글 목록 줄바꿈 반영 및 헤더 고정

- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/components/Buyer/BuyerOpenConsult/HotOpenConsultList.tsx
- src/components/Buyer/BuyerOpenConsultDetail/CommentCard.tsx
- src/components/Common/TabB2.tsx
- src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
- src/components/Seller/SellerOpenConsult/CommentListSection.tsx
- src/pages/Seller/SellerOpenConsult.tsx
<br>
<br>
<br>
- % 상대단위를 사용했습니다.
- gap 대신에 margin을 사용했습니다.
<br>
<br>
사소한 이슈인 거 같아서 ㅎㅎ
<br>
<br>
<br>
> [Hotfix] 시간 선택 모달 디바이스에 따라 스타일 깨짐 오류

- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/components/Buyer/BuyerOpenConsult/HotOpenConsultList.tsx
- src/components/Buyer/BuyerOpenConsultDetail/CommentCard.tsx
- src/components/Common/TabB2.tsx
- src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
- src/components/Seller/SellerOpenConsult/CommentListSection.tsx
- src/pages/Seller/SellerOpenConsult.tsx
Reverts sharemindteam/sharemind-client#245
> Revert "[Hotfix] 시간 선택 모달 디바이스에 따라 스타일 깨짐 오류"

- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/components/Buyer/BuyerOpenConsult/HotOpenConsultList.tsx
- src/components/Buyer/BuyerOpenConsultDetail/CommentCard.tsx
- src/components/Common/TabB2.tsx
- src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
- src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
- src/components/Seller/SellerOpenConsult/CommentListSection.tsx
- src/pages/Seller/SellerOpenConsult.tsx
Reverts sharemindteam/sharemind-client#246
> Revert "Revert "[Hotfix] 시간 선택 모달 디바이스에 따라 스타일 깨짐 오류""

- src/components/Buyer/BuyerConsult/BuyerConsultChatSection.tsx
- src/components/Buyer/Common/ConsultCard.tsx
<br>
<br>
<br>
셰어 사이드 urean count 안보이는 이슈 수정
<br>
<br>
#259 
<br>
<br>
styled component에 $ 문자열이 추가돼어있었습니다...😱
```
background-$color: ${Green};
```
<br>
> [Hotfix] 셰어 사이드 uread count 안보이는 이슈

- src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
<br>
<br>
<br>
리뷰 줄바꿈 처리 안되는 이슈 해결
<br>
<br>
#257 
<br>
<br>
`formattedMessage` 추가하였습니다~
<br>
> [Hotfix] 리뷰 줄바꿈 처리 안되는 이슈 해결

- src/Router.tsx
- src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
- src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
- src/components/Buyer/BuyerCounselorProfile/CounselorProfileHeader.tsx
- src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorCard.tsx
- src/components/Buyer/Common/ReadyConsultCard.tsx
- src/pages/Buyer/BuyerConsultRequest.tsx
- src/pages/Buyer/BuyerCounselorProfile.tsx
- src/pages/Buyer/BuyerPaymentDetail.tsx
<br>
<br>
<br>
지원하는 상담 방식만 선택할 수 있게 수정하였습니다!
<br>
<br>
#242 
<br>
<br>
`counselorId`에 대해서는 모두 params로 넘기게 구현하였고, 그 외의 state에 대해서는 `useLocation` 을 이용하였습니다!
<br>
> [Refactor] 사용가능한 상담 방식만 선택할 수 있게 수정

- src/components/Buyer/BuyerChat/BuyerChatSection.tsx
- src/pages/Buyer/BuyerChat.tsx
<br>
<br>
<br>
마지막 채팅이 후기 작성하기일 경우 inactive, 상담 종료하기 시 inactive로 되게끔 수정하였습니다. 확인 부탁드립니다!
<br>
<br>
#262 
<br>
> feat: apply inactive when chat is finished (#262)

- src/components/Seller/SellerHome/OnGoingConsultSection.tsx
- src/contexts/StompContext.tsx
<br>
<br>
<br>
마인더 홈화면에서 진행 중인 상담이 채팅일 시 ws 연결되도록 수정하고, stomp provider에서 개선작업 진행하였습니다.
<br>
<br>
#266 
<br>
> [Feature] 마인더 홈화면 ws 연결 및 stomp provider 개선

- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/components/Seller/SellerHome/OnGoingConsultSection.tsx
- src/contexts/StompContext.tsx
<br>
<br>
<br>
셰어 홈에서 로그인 시 진행중인 상담이 0일 때의 view가 나타나지 않습니다.
<br>
<br>
#271 
<br>
<br>
추가적으로 진행 중인 상담이 없을 때, chat을 연결하려하여 오류가 발생하는 케이스가 있어 해당 케이스도 막아두었습니다!
<br>
> [Hotfix] 셰어 홈에서 로그인 시 진행중인 상담이 0일 때의 view가 나타나지 않습니다.

- src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
- src/components/Seller/SellerHome/OnGoingConsultSection.tsx
<br>
<br>
<br>
더욱 클린한 동작을 위해 셰어 홈 진행중인 상담에서도 stomp subscription을 이용하여 연결을 관리합니다.
<br>
<br>
#273 
<br>
> [Refactor] 셰어 홈 진행중인 상담에서도 stomp subscription을 이용하여 연결을 관리합니다.

- src/pages/Buyer/BuyerChat.tsx
- src/pages/Seller/SellerChat.tsx
- src/ws/useCounselorChat.ts
- src/ws/useCustomerChat.ts
<br>
<br>
<br>
send 함수를 ws 디렉토리 커스텀 훅으로 리펙토링하였습니다.
<br>
<br>
#270 
<br>
<br>
간단하게  확인 부탁드립니다!
<br>
> [Refactor] send 함수를 ws 디렉토리 커스텀 훅으로 리펙토링

- src/pages/Buyer/BuyerSavedCounselor.tsx
<br>
<br>
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>
<br>
<br>
> Hotfix: 찜 목록 문구 수정

- src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
<br>
<br>
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>
<br>
<br>
> chore: fix counselor info layout

- src/App.Layout.tsx
<br>
<br>
<br>
배경 이미지 레이아웃 꺠지는 이슈 빠르게 수정하였습니다.
<br>
<br>
#304 
<br>
> [Hotfix] 배경 이미지 레이아웃 깨짐 수정

- public/index.html
<br>
<br>
<br>
구글 애널리틱스 코드 추가하였습니다!
<br>
<br>
[참고자료](https://velog.io/@slight-snow/React.js-GA4Google-Analytics-4-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0)
<br>
> [Feat] 구글 애널리틱스 반영

- public/index.html
<br>
<br>
<br>
meta 태그 title, description 변경
<br>
> [Feat] meta 태그 title, description 변경

- src/components/Buyer/BuyerPaymentDetail/PaymentDetailInfo.tsx
- src/components/Buyer/Common/ReadyConsultCard.tsx
- src/components/Common/AppContainer.tsx
- src/pages/Buyer/BuyerOpenPaymentDetail.tsx
- src/pages/Buyer/BuyerPaymentDetail.tsx
<br>
<br>
<br>
결제 안내 페이지 레이아웃 및 워딩 변경사항 반영한 PR입니다.
<br>
<br>
#325 
<br>
<br>
[Figma](https://www.figma.com/design/cZgzroEqmJBGoHvRsTLzmX/sharemind-UI?node-id=5481-68603&t=2yf8FmV91MO6eu2X-0)
<br>
> [Feat] 결제 안내 페이지 레이아웃 수정

- src/pages/Buyer/BuyerFinishPayment.tsx
<br>
<br>
<br>
기존 상담 신청 완료 페이지를 결제 신청 완료 페이지로 변경하였습니다.
<br>
<br>
#326 
<br>
<br>
link는 link 연결 이슈에서 연결해야합니다!
<br>
> [Feat] 베타 테스트 안내 페이지 레이아웃 구현

- src/components/Buyer/BuyerLetter/LetterMainSection.tsx
<br>
<br>
<br>
location state 오류
<br>
> fix: add exception for location state

- src/components/Seller/SellerCalculateManagement/NoCalculationGraphic.tsx
<br>
<br>
<br>
승민님께서 어제 구두로 삭제해달라하셔서 삭제한 PR입니다!
<br>
> [Chore] 수익 관리 subtitle 삭제

- src/components/Common/Header.tsx
<br>
<br>
<br>
마인더 헤더 레이아웃이 깨져서 셰어마인드 베타로고 반영하였습니다!
<br>
<br>
#327 
<br>
<br>
<br>
> [Hotfix] 마인더 홈 헤더에서 셰어마인드 베타로고 첨부

- public/index.html
<br>
<br>
<br>
ms-clarity tag `index.html`에 추가한 PR입니다!
<br>
> feat: add clarity tag

- src/components/Buyer/BuyerAvailCounselor/AvailCounselorSearchResult.tsx
- src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
- src/pages/Buyer/BuyerCategoryResult.tsx
- src/utils/type.ts
<br>
<br>
<br>
들준마, 카테고리 검색 페이지 empty view 추가하였습니다.
<br>
<br>
#347 
<br>
> [Feat] 들준마, 카테고리 검색 페이지 empty view 추가

- src/App.Layout.tsx
- src/components/Common/AppContainer.tsx
<br>
<br>
<br>
`App.Layout.tsx`에 height를 `100vh`로 설정하면서 모바일에서 추가 스크롤이 생겨 수정하였습니다.
<br>
<br>
#352 
<br>
> chore: change resize hook location (#352)

- public/index.html
- src/global.d.ts
- src/pages/Buyer/BuyerPaymentDetail.tsx
- src/utils/requestPayment.ts
- src/utils/type.ts
<br>
<br>
<br>
BuyerOpenPaymentDetail에서 결제 금액, 상담 타입을 팝업 결제창에 뜨도록 구현하였습니다.
<br>
<br>
#365 
<br>
<br>
<br>
> [Feature] Payapp 결제 api 연동

- src/pages/Buyer/BuyerOpenPaymentDetail.tsx
- src/utils/requestPayment.ts
<br>
<br>
<br>
- Payapp API 요청 시 smuse params n에서 y로 설정
- 비공개상담 결제 시 body에 price를 1000으로 설정 
<br>
<br>
<br>
<br>
<br>
> [Hotfix] 7월 29일 수정사항 2가지

- src/components/Seller/SellerOpenConsult/MainQuestionSection.tsx
- src/pages/Seller/SellerMyPageModifyProfile.tsx
<br>
<br>
<br>
마인더 공개상담 비공개 여부 수정
<br>
<br>
#374 
<br>
<br>
조건문이 반대로 돼있었습니다!
<br>
> [Hotfix] 마인더 공개상담 비공개 여부 수정

- src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
<br>
<br>
<br>
[Issue 설명](https://w1696598846-dky839981.slack.com/archives/C06M1AD8RSN/p1722666413596169)
<br>
<br>
-
<br>
<br>
공개상담 신청, 비공개상담 결제 시 가이드 텍스트 수정했습니다.
<br>
> 공개상담 신청, 비공개상담 결제했을 때 가이드 텍스트 수정

- src/components/Buyer/BuyerPaymentDetail/PaymentDetailInfo.tsx
- src/components/Common/Flex.tsx
- src/pages/Buyer/BuyerConsultRequest.tsx
- src/pages/Buyer/BuyerPaymentDetail.tsx
- src/styles/font.tsx
<br>
<br>
<br>
결제 플로우와 상담신청 UI 변경된것 구현했습니다, 이슈 참고부탁드립니다!
<br>
<br>
#385 
<br>
<br>
- 디자인에 새로운 폰트가 추가돼서 `font.tsx` 에 Body5, Body6로서 추가했습니다.
- `Flex.tsx` 에 padding이랑 margin props로 추가했습니다.
<br>
> [Feature] 결제 플로우 구현 및 상담신청 UI 변경

- src/api/post.ts
- src/pages/Buyer/BuyerOpenPaymentDetail.tsx
- src/pages/Buyer/BuyerPaymentDetail.tsx
<br>
<br>
<br>
상담 신청 api 로직 수정 및 일대다 상담 신청 결제 로직 수정
<br>
> [Chore] 상담 신청 api 로직 수정 및 일대다 상담 신청 결제 로직 수정

- public/index.html
<br>
<br>
<br>
gtag 추가
<br>
<br>
#393 
<br>
> [Chore] gtag 추가

- src/pages/Buyer/BuyerOpenConsultRequest.tsx
<br>
<br>
<br>
공개 상담인 경우에 default 전화번호 들어가도록 수정하였습니다!
<br>
> [Hotfix] 공개상담 요청 시 phone number 오류 수정

- src/components/Seller/Common/OngoingCounsultBox.tsx
- src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
<br>
<br>
<br>
마인더 편지 캐릭터 매치 안되는 이슈 수정
<br>
> [Hotfix] 마인더 편지 캐릭터 매치 안되는 이슈 수정

- src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
- src/pages/Seller/SellerMyPageViewProfile.tsx
<br>
<br>
<br>
판매 정보확인하는 전화번호 필드를 추가했습니다! 이슈 참고해주세요
<br>
<br>
#396 
<br>
<br>
<br>
> [Hotfix] 판매정보 확인에 전화번호 필드 추가

- src/components/Seller/SellerLetter/LetterBonusQuestionStep.tsx
- src/components/Seller/SellerLetter/LetterBonusReplyStep.tsx
- src/components/Seller/SellerLetter/LetterQuestionStep.tsx
- src/components/Seller/SellerLetter/LetterReplyStep.tsx
- src/components/Seller/SellerLetterWrite/LetterWriteHeader.tsx
- src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
<br>
<br>
<br>
* 마인더 Letter padding으로 메세지 가리는 이슈 수정
* 추가로 질문 보기 줄바꿈 안돼서 `formattedMessage` 처리
<br>
<br>
#403 
<br>
<br>
간단하게 확인 부탁드립니다!
<br>
> [Hotfix] 마인더 Letter padding으로 메세지 가리는 이슈 수정

- src/components/Seller/SellerOpenConsult/IsSendPopup.tsx
<br>
<br>
<br>
공개 상담 댓글 모달 워딩 수정
<br>
<br>
#406 
<br>
<br>
워딩 수정이라 머지 부탁드립니다!
<br>
> [Chore] 공개 상담 댓글 모달 워딩 수정

- src/components/Common/AppContainer.tsx
- src/pages/Seller/SellerOpenConsult.tsx
- src/styles/AppStyle.ts
<br>
<br>
<br>
* `AppStyle.ts`에 `APP_HEIGHT` 추가하여 앞으로 `calc(var(--vh, 1vh) * 100)` 대신 사용하면 될 것 같습니다.
<br>
<br>
#380 
<br>
> [Hotfix] 마인더 공개상담 focus 빠지지 않는 이슈 수정

- src/components/Buyer/BuyerOpenConsultDetail/CommentListSection.tsx
- src/components/Common/HomeAboutFooterSection.tsx
- src/components/Common/Profile.tsx
- src/components/Seller/SellerChat/ChatReportModal.tsx
- src/pages/Buyer/BuyerLetter.tsx
- src/pages/Buyer/BuyerMypage.tsx
- src/pages/Seller/SellerLetter.tsx
<br>
<br>
<br>
변경된 service center, report url env 반영하였습니다.
<br>
<br>
#405 
<br>
> [Feat] 변경된 service center url 반영

- src/components/Buyer/BuyerOpenConsult/OpenConsultCard.tsx
<br>
<br>
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>
<br>
<br>
> chore: fix openConsultCard align issue

- generateSitemap.mjs
- package-lock.json
- package.json
- src/components/Buyer/BuyerOpenConsultDetail/MainQuestionSection.tsx
- src/pages/Buyer/BuyerCounselorProfile.tsx
<br>
<br>
<br>
SEO를 위한 react-helmet 추가
<br>
<br>
#426 
<br>
> [Feat] SEO를 위한 react-helmet 추가
