src/api/axios.ts
src/api/get.ts
src/api/post.ts
src/components/Buyer/BuyerSearch/SearchHeader.tsx
src/pages/Buyer/BuyerCounselorProfile.tsx
src/pages/Buyer/BuyerMypage.tsx

<br>
<br>
<br>
내정보 페이지 구매자 구현완료 및 public instance 추가
<br>

[Feature] 내정보 페이지 구매자 구현완료 및 public instance 추가

---

package-lock.json
package.json
src/components/Seller/SellerChat/ChatBottomSection.tsx
src/components/Seller/SellerChat/ChatListSection.tsx

<br>
<br>
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>

[Featrue] 채팅 시작, 몇가지 예외처리

---

src/components/Common/Input.tsx
src/components/Common/TagLetterStatus.tsx
src/components/Seller/Common/OngoingCounsultBox.tsx
src/components/Seller/SellerConsult/SellerConsultSection.tsx
src/components/Seller/SellerLetter/LetterTagListSection.tsx
src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
src/components/Skeleton/ConsultCardSkeleton.tsx
src/pages/Seller/SellerLetter.tsx
src/pages/Seller/SellerMyPageModifyProfile.tsx
src/pages/Seller/SellerMyPageViewProfile.tsx

<br>
<br>
<br>
PR 내용을 작성해주세요.
<br>
<br>
<br>

[Feature] 디자인 자잘한 수정 

---

src/contexts/StompContext.tsx
src/pages/Buyer/BuyerLogin.tsx

<br>
<br>
<br>
로그인 시 웹소켓 끊어지는 문제 fix
<br>

[Hotfix] connect when login

---

.github/pull_request_Template.md
src/contexts/StompContext.tsx
src/pages/Buyer/BuyerChat.tsx
src/pages/Seller/SellerChatTemp.tsx

<br>
<br>
<br>
* chat page 메세지 전송 시에 키보드 안 내려가게 수정
* 한글 마지막 글자 겹쳐나오는 이슈 hidden input으로 해결
* 💫chore: pr template에 issue number 추가
<br>
<br>
#169 #171 
<br>

hotfix: maintain keyboard submit

---

src/api/get.ts
src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
src/components/Seller/SellerConsult/SellerChatList.tsx

<br>
<br>
<br>
websocket 백엔드 변경 사항 반영
<br>
<br>
#204 
<br>
<br>
백엔드 웹소켓 바뀐 로직 반영하고 클린 코드로 조금 더 개선하였습니다.
<br>

[Feature] websocket 백엔드 변경 사항 반영

---

src/components/Seller/SellerMyPageModifyProfile/ModifyProfileHeader.tsx
src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
src/pages/Seller/SellerMyPageModifyProfile.tsx

<br>
<br>
<br>
1. 판매 정보 수정 페이지 모달 backdrop 클릭 시 close 되도록 수정
2. 시간 선택 창 닫기 시 수정하기 끝나는 이슈까지 한꺼번에 수정
<br>
<br>
#209 
<br>
<br>
확인 부탁드립니다!
<br>

[Hotfix] 판매 정보 수정 페이지 모달 backdrop 클릭 시 close 되도록 수정

---

src/pages/Buyer/BuyerWriteOpenConsult.tsx

<br>
<br>
<br>
스크롤 짤림 이슈 해결했습니다!
60vh => 50vh 로 수정하였고, 동일하게 마인더 셰어 편지 상담도 디자인 통일이 필요할거 같습니다.
<br>
<br>
#225 
<br>
<br>
<br>

[QA] 공개 상담 작성 페이지 모바일 짤림 이슈 해결

---

src/api/get.ts
src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
src/components/Common/Profile.tsx
src/components/Seller/Common/BankSelectModal.tsx
src/components/Seller/SellerOpenConsult/BottomSection.tsx
src/pages/Buyer/BuyerPayment.tsx
src/pages/Seller/SellerMypage.tsx
src/pages/Seller/SellerRefundBankAccount.tsx

<br>
<br>
<br>
- 공개상담에서 상담사가 댓글 작성했을 여부를 얻어내는 api연동하여 댓글 작성하기 버튼을 댓글 작성 여부에 따라 비활성화하고 클릭이벤트를 막았습니다.
- 정보가 없는 상담사의 consultStyle이 null이어서  Char num이 매핑이 안돼서 view가 깨져서, 기본으로 들어가는 캐릭터를 4번으로 임의로 설정하였습니다.
- 상담사 결제내역 페이지에서 헤더 고정했습니다.
<br>
<br>
<br>
<br>
가볍게 봐주세여
<br>

[Hotfix] 공개상담 댓글 썻을 경우 버튼 비활성화 + 추가적으로 자잘한 것 2가지 구현

---

src/components/Buyer/BuyerSearch/SearchRecent.tsx
src/components/Common/Header.tsx
src/components/Common/Profile.tsx
src/components/Common/TabA1.tsx
src/components/Seller/SellerHome/ConsultReviewsSection.tsx
src/components/Seller/SellerMyPageReview/SellerReviewHeader.tsx
src/pages/Seller/SellerMyPageModifyProfile.tsx
src/pages/Seller/SellerMyPageViewProfile.tsx
src/utils/isIncludeSpecialLetter.ts

<br>
<br>
<br>
사소하면서 치명적인 오류 2가지 고쳤습니다. (이슈 참고부탁드립니다!) 
1. 검색 결과 페이지에서 쿼리 파라미터로 검색어를 조회하는데,  SearchRecent.tsx  에서 최근 검색어를 전역변수(recoil)로 보내주고 있어서  쿼리스트링 형태로 빠르게 수정해 보았습니다~
2. 마인더 입장에서 로그인 하지 않거나 마인더 인증 통과 전에 공개상담 탭 접근 했을 경우 alert 띄우면서 공개상담 탭의 활성화를 막았습니다.
<br>
<br>
#237 
#239 
<br>
<br>
가볍게 봐주세용
<br>

[Hotfix] 최근 검색어 클릭 시 쿼리 파라미터로써 keyword 추가, 인증되지 않은 경우 공개상담 탭 접근 막고 alert 띄우기

---

src/components/Buyer/Common/ConsultCard.tsx

<br>
<br>
<br>
상담 종료시 상담 카드 리뷰 안뜨는 이슈 수정
<br>
<br>
#241 
<br>
<br>
boolean값을 반대로 체크하고 있었네요...!
<br>

[Hotfix] 상담 종료시 상담 카드 리뷰 안뜨는 이슈 수정

---

src/components/Buyer/BuyerCounselorProfile/CounselorExp.tsx
src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
src/components/Buyer/Common/ReadyConsultCard.tsx

<br>
<br>
<br>
이용 가능한 상담 방식에 대한 요금만 보이도록 수정
<br>
<br>
#240 
<br>
<br>
간단하게 삼항연산자로 수정하였습니다~
<br>

[Hotfix] 이용 가능한 상담 방식에 대한 요금만 보이도록 수정

---

src/components/Buyer/BuyerChat/BuyerChatSection.tsx
src/components/Buyer/BuyerConsult/BuyerConsultChatSection.tsx
src/components/Common/AppContainer.tsx
src/components/Seller/SellerConsult/SellerChatList.tsx
src/contexts/StompContext.tsx
src/pages/Buyer/BuyerChat.tsx
src/pages/Seller/SellerChat.tsx
src/utils/atom.ts
src/ws/useCounselorChat.ts
src/ws/useCustomerChat.ts

<br>
<br>
<br>
url을 통한 unsubscribe는 해당 subscription 객체를 unsubscribe 하기 때문에 사용 시 여러개의 중복된 subscribe가 발생하는 이슈가 있었습니다. 
이를 해겷하기 위해 StompSubscription type ref 배열을 이용하여 unsubscribe 하도록 리펙토링하였습니다.
<br>
<br>
#269 
<br>
<br>
해당 브랜치에서 채팅 동작 테스트 및 개발자도구로 메세지가 한번에 여러개 들어오는 케이스가 없는지 확인 부탁드립니다~!
<br>

[Refactor] url을 통한 unsubscribe에서 StompSubscription으로 리펙토링

---

src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
src/components/Buyer/BuyerSignup/SignupVerifyInput.tsx
src/components/Common/AppContainer.tsx
src/components/Common/Button.tsx
src/styles/GlobalStyle.ts

<br>
<br>
<br>
* 이메일 인증 요청 Input 컴포넌트 따로 구현
* 인증 코드 요청 후 pending 시 추가 요청 안 되게 수정 
<br>
<br>
#285 
<br>
<br>
확인 부탁드립니다!
<br>

[Hotfix] 이메일 인증이 계속 눌러지는 이슈 수정

---

src/api/axios.ts
src/contexts/StompContext.tsx

<br>
<br>
axios.ts 에서 `setCookie` 에 액세스 토큰과 리프레쉬 토큰 저장 경로를 항상 /로 조정하여서 쿠키가 /와 /minder에 중복으로 존재하는 이슈를 해결하였습니다.
<br>
#297 
<br>
<br>
<br>

[Bug] /minder URL경로 접속 시 로그인으로 리다이렉트되는 문제 해결

---

src/components/Common/AppHeader.tsx
src/styles/AppStyle.ts

<br>
<br>
<br>
공개상담 detail 페이지(인기순/최신순) 헤더 스크롤 시 사라지는 이슈 해결
* AppHeader를 fixed로 수정하고, `APP_HEADER_HEIGHT` 추가하였습니다.
<br>
<br>
#303 
<br>
<br>
* header도 기존의 방식 말고 `AppHeader.tsx` 사용하시면 될 것 같습니다!
<br>

[Bug] 공개상담 detail 페이지(인기순/최신순) 헤더 스크롤 시 사라지는 이슈 해결

---

src/components/Common/EmptySection.tsx
src/pages/Buyer/BuyerPayment.tsx
src/pages/Buyer/BuyerReviewManage.tsx

<br>
<br>
<br>
empty section 공통 컴포넌트 구현 및 결제내역, 리뷰 내역에 적용
<br>
<br>
#317 
<br>
<br>
* 혹시 나중에 추가적으로 empty 뷰가 필요하다면 `EmptySection.tsx` 사용하면 될 것 같습니다. 구현한 로직만 한번 확인 부탁드립니다!
<br>

[Feat] empty section 공통 컴포넌트 구현 및 결제내역, 리뷰 내역에 적용

---

src/components/Buyer/BuyerConsult/BuyerConsultLetterSection.tsx
src/components/Buyer/BuyerLetter/LetterMainSection.tsx
src/components/Buyer/Common/ConsultCard.tsx

<br>
<br>
<br>
셰어 편지 종료 시 리뷰 작성하기 버튼 추가하였습니다.
* navigate 시에 `isReviewCompleted` 같이 넘겨서 false일 때만 보이게 조건 추가 하였습니다.
<br>
<br>
#287 
<br>

[Feat] 셰어 편지 종료 시 리뷰 작성하기 버튼 추가

---

src/Router.tsx
src/components/Common/HomeAboutFooterSection.tsx
src/components/Common/Profile.tsx
src/pages/Buyer/BuyerMypage.tsx
src/pages/Buyer/BuyerOpenPaymentDetail.tsx
src/pages/Buyer/BuyerPaymentDetail.tsx

<br>
<br>
<br>
구매, 고객센터 링크 연결
<br>
<br>
#324 
<br>

[Feat] 구매, 고객센터 링크 연결

---

addIssueNumber.sh
package-lock.json
package.json

<br>
<br>
<br>
해당 기능 사용하기 위해 브랜치 컨벤션을 다음과 같이 작성하면 될 것 같습니다!
* 브랜치명 컨벤션: feat/{this_branch_does}_{issue_number} (ex. `feat/add_button_74`)
* 브랜치명에 이슈 넘버 명시해주면 자동으로 commit 시 메세지에 자동으로 할당됩니다. (ex. `chore: add padding (#74)`)
<br>
<br>
#344 
<br>
<br>
혹시 동작 안하면 말해주세용! 
<br>

[Feat] husky로 commit 시 이슈 넘버 자동할당하는 로직 추가

---

src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
src/pages/Seller/SellerMyPageModifyProfile.tsx

<br>
<br>
<br>
판매 정보 수정에서 편지와 채팅의 가격 설정 범위를 3,000~ 30,000원, 5000~50,000원으로 수정하였습니다.
<br>
<br>
#354 
<br>
<br>
아직 서버쪽에서 편지 가격 범위가 설정이 안돼서
https://w1696598846-dky839981.slack.com/archives/C06010RG7PG/p1721184169428489
요청사항 보낸 상태입니다
<br>

[Hotfix] 편지, 채팅 가격 설정 범위 수정

---

src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
src/components/Common/CounselorCard.tsx
src/pages/Buyer/BuyerHome.tsx

<br>
<br>
<br>
모바일에서만 깨지는데, `justify`를 명시해야하는 부분에 `flex-start` 추가하였습니다!
<br>

[Hotfix] 홈화면 들준마 레이아웃 모바일 깨짐 수정

---

.github/ISSUE_TEMPLATE/feature.md
src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorResults.tsx
src/components/Buyer/BuyerSavedCounselor.tsx/SavedOpenConsultResults.tsx
src/components/Common/CounselorCard.tsx
src/pages/Buyer/BuyerSavedCounselor.tsx

<br>
<br>
<br>
기존의 목적은 찜을 취소하면 visiblity를 false로 만드는 방식으로 즉각적으로 반영되는 것처럼 구현하였으나, 엠티 뷰가 안보이는 이슈가 있어 infinite query로 마이그레이션하여 해결하려하였습니다.
하지만 query를 invalidate할 때마다 깜빡임 이슈가 있었고, 다른 래퍼런스 페이지 찾아본 결과 좋아요 혹은 스크랩을 취소해도 바로 없어지지 않게 구현이 돼있어, infinite query로만 변경하게 되었습니다.
<br>
<br>
#350 
<br>

[Feat] 찜 목록 페이지 infinite query로 마이그레이션

---

src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorResults.tsx
src/components/Common/CounselorCard.tsx
src/utils/type.ts

<br>
<br>
<br>
기존에 찜 목록 리스트에 `totalConsult`(상담 횟수)가 없어서 optional 처리하였는데, api에 추가되어 해당 사항 반영하였습니다.
<br>
<br>
#348 
<br>
<br>
확인 부탁드립니다!
<br>

feat: remove optional condition to counselor card `totalConsult` (#348)

---

src/pages/Buyer/BuyerOpenConsultRequest.tsx

<br>
<br>
<br>
공개상담 무료 결제 후에도 결제 신청 완료 페이지가 떠서 혼동되는 이슈가 있어, 바로 상담탭 => 공개상담 태그로 navigate하도록 수정하였습니다.
<br>
<br>
#370 
[Slack](https://w1696598846-dky839981.slack.com/archives/C06M1AD8RSN/p1722418968045079)
<br>

[Feat] 공개상담 결제 플로우 개선

---

src/components/Common/CounselorCard.tsx
src/components/Seller/SellerMyPageReview/ReviewComplaintMenu.tsx
src/components/Seller/SellerOpenConsult/BottomSection.tsx
src/components/Seller/SellerOpenConsult/OpenConsultHeader.tsx
src/hooks/useIsAlreadyReply.ts
src/pages/Seller/SellerMyPageModifyProfile.tsx
src/pages/Seller/SellerOpenConsult.tsx
src/utils/isIncludeSpecialLetter.ts

<br>
<br>
<br>
공개상담 글과 댓글 작성을 동시에 하지못하는 ios 키보드 이슈 해결한 PR입니다.
keyboard event가 발생할때 마다 footer의 bottom 값을 수정하는 방향으로 구현하였습니다.
<br>
<br>
#373
<br>

[Hotfix] 공개상담 ios 키보드 이슈

---

src/api/patch.ts
src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
src/components/Seller/SellerMyPageModifyProfile/UpdatePopup.tsx
src/pages/Seller/SellerMyPageModifyProfile.tsx
src/utils/type.ts

<br>
<br>
<br>
* 전화번호 중복 시 에러 핸들링 로직 추가하였습니다.
* `axiosPatch` 로 수정하면서 기존 error 코드 수정하고, `SharemindErrorResponse` 타입 추가하여 최대한 하드코딩하지 않고, 서버에서 넘겨준 값을 통해 에러 핸들링하도록 수정하였습니다!
<br>
<br>
#381 
<br>
<br>
서버 저장된 전화번호 data를 초기값으로 설정하기 위해 코드 위치만 수정하였고, 에러 핸들링 부분 수정한 것만 한번 확인해주시면 좋을 것 같습니다!
<br>

[Feat] 마인더 전화번호 입력 시 중복 전화번호 에러 핸들링 로직 추가

---

src/components/Buyer/BuyerOpenConsultDetail/CommentCard.tsx
src/components/Buyer/BuyerOpenConsultDetail/CommentListSection.tsx
src/components/Seller/Common/ComplaintModal.tsx
src/components/Seller/SellerChat/ChatReportModal.tsx
src/components/Seller/SellerLetter/LetterHeader.tsx
src/hooks/useShowComplaintModal.ts
src/pages/Buyer/BuyerLetter.tsx
src/pages/Seller/SellerConsult.tsx
src/pages/Seller/SellerLetter.tsx
src/utils/atom.ts

<br>
<br>
<br>
- 더보기 눌렀을 때 신고하기 모달 띄우기 in 편지, 공개상담
<br>
<br>
#398 
<br>
<br>
- 신고하기 모달, `ComplaintModal` 공통 컴포넌트로 추가했습니다.
- 신고하기 모달을 보여주는 로직을 담당하는 `useShowComplaintModal` 훅 추가했습니다.
앞으로 ComplaintModal에 신고하기 로직인 `handleComplaintButtonClick` 을 props로 전달해주는 방식으로 구현하면 될 거 같습니다
<br>

[Hotfix] 신고하기 모달을 편지, 공개 상담 페이지에 추가

---

src/Router.tsx
src/components/Seller/SellerCalculateManagement/CompleteApplyPopup.tsx
src/components/Seller/SellerCalculateManagement/SellerCalculateCard.tsx
src/pages/Seller/SellerCalculateManagement.tsx

<br>
<br>
<br>
- 마인더 정산신청 DTO 업데이트 된 내역 카드에 반영했습니다.
- 무한스크롤 로직 수정해서 잘 동작하는 지 확인해봤습니다.
<br>
<br>
#414 
<br>
<br>
이슈 트래킹 빼먹었습니다 죄송합니다 ..
<br>

마인더 정산신청 페이지 무한스크롤 오류 해결 및 DTO 업데이트

---

public/index.html
src/App.tsx
src/components/Buyer/BuyerOpenConsultDetail/MainQuestionSection.tsx

<br>
<br>
<br>
React Helmet 검색엔진 반영 안되는 이슈 배포 테스트
<br>
<br>
#426 
<br>

[Fix] React Helmet 검색엔진 반영 안되는 이슈 배포 테스트
